# Generated by Django 5.0.14 on 2025-08-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_folder_owner_alter_folder_name_alter_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
